Repository brave-intl/bat-go, pull requests merged in 2023-12, with the labels that each got.

#2239 removing vbat drain logic
  README.md
  libs/clients/bitflyer/client.go
  libs/clients/gemini/client.go
  services/grant/cmd/grant.go
  services/grant/service.go
  services/promotion/controllers.go
  services/promotion/controllers_test.go
  services/promotion/datastore.go
  services/promotion/datastore_test.go
  services/promotion/drain.go
  services/promotion/drain_test.go
  services/promotion/instrumented_datastore.go
  services/promotion/instrumented_read_only_datastore.go
  services/promotion/mockdatastore.go
  services/promotion/mockdrain.go
  services/promotion/service.go
  services/promotion/service_test.go
  services/wallet/instrumented_datastore.go
  services/wallet/instrumented_read_only_datastore.go
  services/wallet/mockservice.go
Labels: needs-security-review, unverified-commits

#2251 Update Go Build and Runtime to 1.19
  .github/workflows/ci.yml
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  Dockerfile
  docker-compose.dev-refresh.yml
  services/rewards/docker-compose.yml
  services/skus/docker-compose.payment-refresh.yml
  services/skus/docker-compose.yml
  services/wallet/docker-compose.yml
  tools/Dockerfile
Labels: unverified-commits

#2252 Fix panic: duplicate metrics collector registration attempted
  docker-compose.dev-refresh.yml
  ecs-vars-dev.env
  libs/clients/bitflyer/instrumented_client.go
  libs/clients/cbr/instrumented_client.go
  libs/clients/coingecko/instrumented_client.go
  libs/clients/gemini/instrumented_client.go
  libs/clients/radom/instrumented.go
  libs/clients/radom/radom.go
  libs/clients/ratios/instrumented_client.go
  libs/clients/reputation/instrumented_client.go
  libs/clients/stripe/instrumented_client.go
  libs/ptr/ptr.go
  services/grant/cmd/grant.go
  services/grant/instrumented_datastore.go
  services/grant/instrumented_read_only_datastore.go
  services/promotion/instrumented_datastore.go
  services/promotion/instrumented_read_only_datastore.go
  services/skus/docker-compose.payment-refresh.yml
  services/skus/docker-compose.yml
  services/skus/instrumented_datastore.go
  services/skus/service_test.go
  services/wallet/instrumented_datastore.go
  services/wallet/instrumented_read_only_datastore.go
Labels: unverified-commits

#2244 production 2023-12-11_1
  .github/workflows/ci.yml
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  Dockerfile
  README.md
  docker-compose.dev-refresh.yml
  ecs-vars-dev.env
  libs/clients/bitflyer/client.go
  libs/clients/bitflyer/instrumented_client.go
  libs/clients/cbr/instrumented_client.go
  libs/clients/coingecko/instrumented_client.go
  libs/clients/gemini/client.go
  libs/clients/gemini/instrumented_client.go
  libs/clients/radom/instrumented.go
  libs/clients/radom/radom.go
  libs/clients/ratios/instrumented_client.go
  libs/clients/reputation/instrumented_client.go
  libs/clients/stripe/instrumented_client.go
  libs/ptr/ptr.go
  services/grant/cmd/grant.go
  services/grant/instrumented_datastore.go
  services/grant/instrumented_read_only_datastore.go
  services/grant/service.go
  services/promotion/controllers.go
  services/promotion/controllers_test.go
  services/promotion/datastore.go
  services/promotion/datastore_test.go
  services/promotion/drain.go
  services/promotion/drain_test.go
  services/promotion/instrumented_datastore.go
  services/promotion/instrumented_read_only_datastore.go
  services/promotion/mockdatastore.go
  services/promotion/mockdrain.go
  services/promotion/service.go
  services/promotion/service_test.go
  services/rewards/docker-compose.yml
  services/skus/controllers.go
  services/skus/docker-compose.payment-refresh.yml
  services/skus/docker-compose.yml
  services/skus/instrumented_datastore.go
  services/skus/service.go
  services/skus/service_test.go
  services/wallet/docker-compose.yml
  services/wallet/mockservice.go
  tools/Dockerfile
Labels: needs-security-review

#2183 Add Endpoints for Submitting and Fetching Credentials Based on Request ID
  services/skus/controllers.go
  services/skus/controllers_test.go
  services/skus/credentials.go
  services/skus/datastore.go
  services/skus/instrumented_datastore.go
  services/skus/mockdatastore.go
  services/skus/model/model.go
  services/skus/model/model_test.go
  services/skus/service.go
Labels: needs-security-review

#2253 Allow country code fallback for linked Gemini users
  libs/clients/gemini/client.go
  libs/clients/gemini/clientx_test.go
  libs/clients/gemini/instrumented_client.go
  libs/clients/gemini/mock/mock.go
  services/promotion/service_test.go
  services/wallet/controllers_v3_test.go
  services/wallet/controllers_v4_test.go
  services/wallet/datastore.go
  services/wallet/datastore_pvt_test.go
  services/wallet/gemini.go
  services/wallet/gemini_test.go
  services/wallet/keystore_test.go
  services/wallet/metric/metric.go
  services/wallet/service.go
Labels: unverified-commits, puLL-Merge

#2271 refactor: rename geminix test
  services/wallet/gemini_test.go
Labels: unverified-commits
