Repository brave-intl/bat-go, pull requests merged in 2024-02, with the labels that each got.

#2332 feat: add specific linking limit error for solana
  services/wallet/controllers_v3.go
  services/wallet/datastore.go
  services/wallet/datastore_pvt_test.go
Labels: unverified-commits

#2339 fix: use equals check for payment id validation instead of govalidator on challenge endpoint
  services/wallet/controllers_v3.go
Labels: unverified-commits

#2331 check for mismatch on tlv2 credential submissions across request ids
  services/skus/controllers.go
  services/skus/credentials.go
  services/skus/datastore.go
  services/skus/datastore_noint_test.go
  services/skus/datastore_test.go
  services/skus/instrumented_datastore.go
  services/skus/mockdatastore.go
Labels: unverified-commits, puLL-Merge

#2344 fix query to check for request id conflict case ( mismatch )
  services/skus/datastore.go
  services/skus/datastore_noint_test.go
  services/skus/datastore_test.go
Labels: unverified-commits

#2355 refactor: remove vbat related jobs
  services/grant/cmd/grant.go
  services/promotion/claim.go
  services/promotion/controllers_test.go
  services/promotion/drain_test.go
  services/promotion/service.go
Labels: unverified-commits

#2358 feat: add terms of service version to parameters endpoint
  schema/rewards/ParametersV1
  services/rewards/cmd/rest_run.go
  services/rewards/controllers_test.go
  services/rewards/parameters.go
  services/rewards/service.go
  services/rewards/service_test.go
Labels: unverified-commits

#2374 Production 2024-02-22_01
  schema/rewards/ParametersV1
  services/rewards/cmd/rest_run.go
  services/rewards/controllers_test.go
  services/rewards/parameters.go
  services/rewards/service.go
  services/rewards/service_test.go
  services/skus/controllers.go
  services/skus/handler/handler_pvt_test.go
  services/skus/model/model.go
  services/skus/model/model_test.go
  services/skus/order.go
  services/skus/order_noint_test.go
  services/skus/order_test.go
  services/skus/service.go
  services/skus/storage/repository/issuer_test.go
  services/skus/storage/repository/order_item_test.go
  services/skus/storage/repository/repository_test.go
  services/wallet/storage/storage_test.go
Labels: needs-security-review

#2375 build: update docker compose command in makefile
  Makefile
Labels: unverified-commits

#2360 fix: validate google submit receipt
  services/skus/controllers.go
  services/skus/controllers_noint_test.go
  services/skus/receipt.go
  services/skus/receipt_test.go
Labels: unverified-commits
