Repository brave-intl/bat-go, pull requests merged in 2025-06, with the labels that each got.

#2864 refactor: add sub back button url to radom checkout session request
  services/skus/controllers_test.go
  services/skus/model/model.go
  services/skus/radom/radom.go
  services/skus/service.go
  services/skus/service_nonint_test.go
Labels: pay-with-bat

#2860 feat: add external request logging
  libs/middleware/request_correlation.go
  libs/middleware/request_logger.go
  services/cmd/serve.go
  services/grant/cmd/grant.go
Labels: technical

#2866 refactor: add sub back button url to radom checkout session top level
  services/skus/controllers_test.go
  services/skus/radom/radom.go
  services/skus/service.go
  services/skus/service_nonint_test.go
Labels: pay-with-bat

#2868 fix: use correct expires at for annual subs when time chunking
  services/skus/model/model.go
  services/skus/model/model_test.go
  services/skus/service.go
  services/skus/service_test.go
Labels: bug
